### ISSUE TITLE
Question about Object Detection on Prophesee GEN1

### ISSUE THREAD

**Issue by xxyll** [loiccordone/object-detection-with-spiking-neural-networks#1]
Hello,

I want to run 'object_detection.py', do I need to download the GEN1 Automotive Detection Dataset myself? (I find the official website about this dataset) 

Thanks in advance.

**Comment by loiccordone** [comment]
Hello,
Yes, you need to download the dataset on the official Prophesee website. Beware as the dataset is quite large (370Go uncompressed).

**Comment by xxyll** [comment]
Firstly, thanks you for your answer!!!

I have a few more questions. Since the dataset is large, can I download one compressed package for debugging code first?

The other question is, after I downloaded the dataset, I unzipped it to the 'object-detection-with-spiking-neural-networks' directory, how do I set up '-dataset' and '-path' in 'object_detection.py'? (line 33 and 34). The above question puzzled me two days...

My English is a little poor...Thank you very much for your patient answer.

**Comment by loiccordone** [comment]
Hi again,

> can I download one compressed package for debugging code first?

Yes of course, the dataset generation will iterate through all the files you have in your directory, it can be a small subset of the dataset.

> how do I set up '-dataset' and '-path' in 'object_detection.py'?

the -dataset parameter supports only the value "gen1", so you don't have to modify it. If you unzipped the dataset in a directory named "PropheseeDataset" for example, just specify the relative path to this directory (in this case, simply "PropheseeDataset").

The pretrained models will be available soon.

Good luck!
