### ISSUE TITLE
ValueError: optimizer got an empty parameter list

### ISSUE THREAD

**Issue by dnkscu** [loiccordone/object-detection-with-spiking-neural-networks#16]
![7C962D12-A521-46E0-95C9-6D59B5619AA0](https://user-images.githubusercontent.com/93386667/201522634-2bd22463-d3b5-412d-a2ee-7a903b4ef42b.png)
Hello dear author, I encountered the error shown in the figure when using this line of code.
`python classification.py -dataset ncars -path path/to/NCARS_dataset -model densenet121-16 -T 5 -tbin 2`
I can't find the file named "densenet121-16" in the source code, where is it defined?
Please take a look at the cause of this problem, thank you!

**Comment by one00101** [comment]
Hi, I meet the same error when I try to run the code, have you solved the problem? Thanks a lot~

**Comment by Alloman** [comment]
According to the statement in the file`./models/utils.py`, the param `-model` should be like 'densenet-121_16' for using DenseNet. This may be a mistake.

**Comment by loiccordone** [comment]
> According to the statement in the file`./models/utils.py`, the param `-model` should be like 'densenet-121_16' for using DenseNet. This may be a mistake.

Yes, you are right. The error raised by a misread model name is not very clear, I should add a check. Thanks!
