### ISSUE TITLE
RuntimeError: "coalesce" not implemented for 'Bool'

### ISSUE THREAD

**Issue by ShristiDasBiswas** [loiccordone/object-detection-with-spiking-neural-networks#19]
How can I solve this error?

![error](https://user-images.githubusercontent.com/99504345/225760406-d2ce735a-fa6c-4f1a-9e61-3d01bcad7f97.png)

**Comment by SamWang-llm** [comment]
I've encountered the same issue (maybe it is because the incompatible version between torch ( version author mentioned is a little bit old) and cuda ).  Have you sovled this issue now?
