### ISSUE TITLE
local variable 'sample' referenced before assignment

### ISSUE THREAD

**Issue by rachmadvwp** [loiccordone/object-detection-with-spiking-neural-networks#30]
Hi Loic,
I tried to run the code for NCARS dataset, but faced the following issue:
```
File "/home/me/objdetectSNN/datasets/classification_datasets.py", line 40, in __getitem__
    sample = sample.sparse_resize_( 
UnboundLocalError: local variable 'sample' referenced before assignment
```
Kindly let me know how to address it properly. 
Many thanks.

**Comment by rachmadvwp** [comment]
I think I have fixed the issue. I'll close it for now. Thanks.

**Comment by hit-gzz** [comment]
excuse me, i also met this problem, could you tell me how you figure it out? much thx!

**Comment by 00kangdonghun** [comment]
I've encountered the same problem. Could you please tell me a solution? I'd appreciate your help.
