### ISSUE TITLE
How to fix the EOFError

### ISSUE THREAD

**Issue by wozcoder** [loiccordone/object-detection-with-spiking-neural-networks#7]
Hello @[xxyll](https://github.com/xxyll)
I have seen that you have created an issue about EOFError. Can you please how you have solved this issue?
Thanks

**Comment by loiccordone** [comment]
As mentioned in #4, the problem certainly comes from the  "OSError: [Errno 24] Too many open files".

> It doesn't seem to come from my code, so you could try some solutions proposed in this stackoverflow thread : [Python Subprocess: Too Many Open Files](https://stackoverflow.com/questions/16526783/python-subprocess-too-many-open-files)

**Comment by wozcoder** [comment]
Yes I understand it. However my question was more about which specific fix did @xxyll used in order to solve this problem.
"sudo sysctl -w fs.file-max=100000" <- this?
or 
another one on the comments

**Comment by wozcoder** [comment]
Ok problem fixed thanks
